const fs = require("fs");
var dir = process.argv[2];
var out = process.argv[3];
var open = "(function(Req){";
var close = "})(Req);";
var d = new Date();
var str = [
	'"use strict";',
	"/*",
	" * Generated by reqpack (" + d.getDate() + "/" + (d.getMonth() + 1) + "/" + d.getFullYear() + ")",
	" */",
	'const Req = require("Req");'
].join("\n");
fs.readdirSync(dir).forEach(file => {
	str += open + fs.readFileSync(file).toString() + close;
});

if(out) fs.writeFileSync(out, str);
else process.stdout.write(str);