#!bin/env node --harmony
const fs  = require("fs");
var main  = process.argv[2];
var dir   = process.argv[3];
if(!main || !dir) {
	console.log(
		`Usage:
			reqpack <main> <dir> [out]
		
		Where:
			<main> is the main file to be exported
			<dir>  is the directory to bundle
			[out]  the file to output to (default: stdout)`
	); process.exit(0);
}
var out   = process.argv[4];
var open  = "(function(Req){return ";
var close = "})(Req);";
var mstr  = "module.exports = exports = ";
var d     = new Date();
var str   = [
	'"use strict";',
	"/*",
	" * Generated by reqpack (" + d.getDate() + "/" + (d.getMonth() + 1) + "/" + d.getFullYear() + ")",
	" */",
	'const Req = require("Req");'
].join("\n");
fs.readdirSync(dir).forEach(file => {
	str += (file === main ? mstr : "") + open + fs.readFileSync(file).toString() + close;
});

if(out) fs.writeFileSync(out, str);
else process.stdout.write(str);